# .github/workflows/ci.yml
name: CI

on:
  push:
  pull_request:

permissions:
  contents: read
  actions: read
  pull-requests: write
  checks: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - run: npm ci
      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - run: npm ci
      - name: Run tests and generate report
        run: npx allure run -- npm run test
      - run: ls -clash .; ls -clash allure-report/
      - name: Run Allure Action
        uses: allure-framework/allure-action@v0
        with:
          report-directory: "./allure-report"
      - name: Upload Allure Report (optionnel)
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
